[build]
  command = "npm ci && npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[[edge_functions]]
  path = "/player/*"
  function = "rewrite2"