[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"
  
[build.environment]
  NEXT_PUBLIC_API_URL = "https://your-deployed-api-url.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["!node_modules/**", "/tmp/*.log"]

[[edge_functions]]
  path = "/player/*"
  function = "rewrite"
